// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3elWhd4pZJAYi-GM8d3z9xmxmkWvipw',
    appId: '1:800572407227:android:660b128a1ae7ab0de0989e',
    messagingSenderId: '800572407227',
    projectId: 'earthquakeapp-d43af',
    storageBucket: 'earthquakeapp-d43af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs7icBneTppAe_8HEmBU9WEkxaMmWm18Q',
    appId: '1:800572407227:ios:442bc23ae7f85d50e0989e',
    messagingSenderId: '800572407227',
    projectId: 'earthquakeapp-d43af',
    storageBucket: 'earthquakeapp-d43af.appspot.com',
    iosClientId: '800572407227-h95iq2vqe2skqgraa9tufpo9qbla1v8o.apps.googleusercontent.com',
    iosBundleId: 'net.narikakun.earthquakeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs7icBneTppAe_8HEmBU9WEkxaMmWm18Q',
    appId: '1:800572407227:ios:cd9d4beedae370dce0989e',
    messagingSenderId: '800572407227',
    projectId: 'earthquakeapp-d43af',
    storageBucket: 'earthquakeapp-d43af.appspot.com',
    iosClientId: '800572407227-c2nt1jqgsma2hdlq8tgoteec081qmfgn.apps.googleusercontent.com',
    iosBundleId: 'net.narikakun.earthquakeApp.RunnerTests',
  );
}
